python metrics.py predictions/wood/scratch/scratched_surface.pt
python metrics.py predictions/wood/scratch/broken.pt
python metrics.py predictions/wood/scratch/damage.pt
python metrics.py predictions/wood/scratch/damaged.pt
python metrics.py predictions/zipper/broken_teeth/broken_teeth.pt
python metrics.py predictions/zipper/broken_teeth/broken_tooth.pt
python metrics.py predictions/zipper/broken_teeth/split_teeth.pt
python metrics.py predictions/zipper/broken_teeth/broken_zipper.pt
python metrics.py predictions/zipper/broken_teeth/faulty_zipper.pt
python metrics.py predictions/zipper/broken_teeth/broken.pt
python metrics.py predictions/zipper/broken_teeth/damage.pt
python metrics.py predictions/zipper/broken_teeth/damaged.pt
python metrics.py predictions/zipper/fabric_border/damaged_fabric.pt
python metrics.py predictions/zipper/fabric_border/cut.pt
python metrics.py predictions/zipper/fabric_border/broken.pt
python metrics.py predictions/zipper/fabric_border/damage.pt
python metrics.py predictions/zipper/fabric_border/damaged.pt
python metrics.py predictions/zipper/fabric_interior/damaged_fabric.pt
python metrics.py predictions/zipper/fabric_interior/holes.pt
python metrics.py predictions/zipper/fabric_interior/damaged_surface.pt
python metrics.py predictions/zipper/fabric_interior/broken.pt
python metrics.py predictions/zipper/fabric_interior/damage.pt
python metrics.py predictions/zipper/fabric_interior/damaged.pt
python metrics.py predictions/zipper/rough/rough_teeth.pt
python metrics.py predictions/zipper/rough/rough_tooth.pt
python metrics.py predictions/zipper/rough/rough_edges.pt
python metrics.py predictions/zipper/rough/rough_zipper.pt
python metrics.py predictions/zipper/rough/broken.pt
python metrics.py predictions/zipper/rough/damage.pt
python metrics.py predictions/zipper/rough/damaged.pt
python metrics.py predictions/zipper/split_teeth/split_teeth.pt
python metrics.py predictions/zipper/split_teeth/broken_teeth.pt
python metrics.py predictions/zipper/split_teeth/broken_zipper.pt
python metrics.py predictions/zipper/split_teeth/faulty_zipper.pt
python metrics.py predictions/zipper/split_teeth/broken.pt
python metrics.py predictions/zipper/split_teeth/damage.pt
python metrics.py predictions/zipper/split_teeth/damaged.pt
python metrics.py predictions/zipper/squeezed_teeth/squeezed_teeth.pt
python metrics.py predictions/zipper/squeezed_teeth/broken_teeth.pt
python metrics.py predictions/zipper/squeezed_teeth/broken_zipper.pt
python metrics.py predictions/zipper/squeezed_teeth/broken.pt
python metrics.py predictions/zipper/squeezed_teeth/damage.pt
python metrics.py predictions/zipper/squeezed_teeth/damaged.pt
