python experiment.py --config configs/bottle_broken_large_broken_glass.yaml
python experiment.py --config configs/bottle_broken_large_broken_bottle.yaml
python experiment.py --config configs/bottle_broken_large_broken.yaml
python experiment.py --config configs/bottle_broken_large_damage.yaml
python experiment.py --config configs/bottle_broken_large_damaged.yaml
python experiment.py --config configs/bottle_broken_small_broken_glass.yaml
python experiment.py --config configs/bottle_broken_small_broken_bottle.yaml
python experiment.py --config configs/bottle_broken_small_broken.yaml
python experiment.py --config configs/bottle_broken_small_damage.yaml
python experiment.py --config configs/bottle_broken_small_damaged.yaml
python experiment.py --config configs/bottle_contamination_foreign_objects.yaml
python experiment.py --config configs/bottle_contamination_contaminated.yaml
python experiment.py --config configs/bottle_contamination_broken.yaml
python experiment.py --config configs/bottle_contamination_damage.yaml
python experiment.py --config configs/bottle_contamination_damaged.yaml
python experiment.py --config configs/cable_bent_wire_bent_wire.yaml
python experiment.py --config configs/cable_bent_wire_malformed_wire.yaml
python experiment.py --config configs/cable_bent_wire_broken.yaml
python experiment.py --config configs/cable_bent_wire_damage.yaml
python experiment.py --config configs/cable_bent_wire_damaged.yaml
python experiment.py --config configs/cable_cable_swap_cables_with_same_colors.yaml
python experiment.py --config configs/cable_cable_swap_swapped_cables.yaml
python experiment.py --config configs/cable_cable_swap_broken.yaml
python experiment.py --config configs/cable_cable_swap_damage.yaml
python experiment.py --config configs/cable_cable_swap_damaged.yaml
python experiment.py --config configs/cable_cut_inner_insulation_cut_insulation.yaml
python experiment.py --config configs/cable_cut_inner_insulation_damaged_insulation.yaml
python experiment.py --config configs/cable_cut_inner_insulation_broken.yaml
python experiment.py --config configs/cable_cut_inner_insulation_damage.yaml
python experiment.py --config configs/cable_cut_inner_insulation_damaged.yaml
python experiment.py --config configs/cable_cut_outer_insulation_cut_insulation.yaml
python experiment.py --config configs/cable_cut_outer_insulation_damaged_insulation.yaml
python experiment.py --config configs/cable_cut_outer_insulation_broken.yaml
python experiment.py --config configs/cable_cut_outer_insulation_damage.yaml
python experiment.py --config configs/cable_cut_outer_insulation_damaged.yaml
python experiment.py --config configs/cable_missing_cable_empty_cable.yaml
python experiment.py --config configs/cable_missing_cable_hole.yaml
python experiment.py --config configs/cable_missing_cable_missing_cable.yaml
python experiment.py --config configs/cable_missing_cable_broken.yaml
python experiment.py --config configs/cable_missing_cable_damage.yaml
python experiment.py --config configs/cable_missing_cable_damaged.yaml
python experiment.py --config configs/cable_missing_wire_empty_cable.yaml
python experiment.py --config configs/cable_missing_wire_empty_wire.yaml
python experiment.py --config configs/cable_missing_wire_hole.yaml
python experiment.py --config configs/cable_missing_wire_missing_wire.yaml
python experiment.py --config configs/cable_missing_wire_broken.yaml
python experiment.py --config configs/cable_missing_wire_damage.yaml
python experiment.py --config configs/cable_missing_wire_damaged.yaml
python experiment.py --config configs/cable_poke_insulation_damaged_insulation.yaml
python experiment.py --config configs/cable_poke_insulation_hole_in_insulation.yaml
python experiment.py --config configs/cable_poke_insulation_poke_insulation.yaml
python experiment.py --config configs/cable_poke_insulation_broken.yaml
python experiment.py --config configs/cable_poke_insulation_damage.yaml
python experiment.py --config configs/cable_poke_insulation_damaged.yaml
python experiment.py --config configs/capsule_crack_crack.yaml
python experiment.py --config configs/capsule_crack_cracked.yaml
python experiment.py --config configs/capsule_crack_cracked_capsule.yaml
python experiment.py --config configs/capsule_crack_broken.yaml
python experiment.py --config configs/capsule_crack_damage.yaml
python experiment.py --config configs/capsule_crack_damaged.yaml
python experiment.py --config configs/capsule_faulty_imprint_faulty_text.yaml
python experiment.py --config configs/capsule_faulty_imprint_faulty_imprint.yaml
python experiment.py --config configs/capsule_faulty_imprint_broken.yaml
python experiment.py --config configs/capsule_faulty_imprint_damage.yaml
python experiment.py --config configs/capsule_faulty_imprint_damaged.yaml
python experiment.py --config configs/capsule_poke_hole.yaml
python experiment.py --config configs/capsule_poke_damaged_capsule.yaml
python experiment.py --config configs/capsule_poke_poke.yaml
python experiment.py --config configs/capsule_poke_broken.yaml
python experiment.py --config configs/capsule_poke_damage.yaml
python experiment.py --config configs/capsule_poke_damaged.yaml
python experiment.py --config configs/capsule_scratch_scratch.yaml
python experiment.py --config configs/capsule_scratch_scratched_capsule.yaml
python experiment.py --config configs/capsule_scratch_broken.yaml
python experiment.py --config configs/capsule_scratch_damage.yaml
python experiment.py --config configs/capsule_scratch_damaged.yaml
python experiment.py --config configs/capsule_squeeze_squeezed.yaml
python experiment.py --config configs/capsule_squeeze_squeezed_capsule.yaml
python experiment.py --config configs/capsule_squeeze_broken.yaml
python experiment.py --config configs/capsule_squeeze_damage.yaml
python experiment.py --config configs/capsule_squeeze_damaged.yaml
python experiment.py --config configs/carpet_color_color.yaml
python experiment.py --config configs/carpet_color_colored_strokes.yaml
python experiment.py --config configs/carpet_color_stains.yaml
python experiment.py --config configs/carpet_color_stain.yaml
python experiment.py --config configs/carpet_color_broken.yaml
python experiment.py --config configs/carpet_color_damage.yaml
python experiment.py --config configs/carpet_color_damaged.yaml
python experiment.py --config configs/carpet_cut_hole.yaml
python experiment.py --config configs/carpet_cut_cut.yaml
python experiment.py --config configs/carpet_cut_cuts.yaml
python experiment.py --config configs/carpet_cut_tear.yaml
python experiment.py --config configs/carpet_cut_broken.yaml
python experiment.py --config configs/carpet_cut_damage.yaml
python experiment.py --config configs/carpet_cut_damaged.yaml
python experiment.py --config configs/carpet_hole_hole.yaml
python experiment.py --config configs/carpet_hole_cut.yaml
python experiment.py --config configs/carpet_hole_tear.yaml
python experiment.py --config configs/carpet_hole_broken.yaml
python experiment.py --config configs/carpet_hole_damage.yaml
python experiment.py --config configs/carpet_hole_damaged.yaml
python experiment.py --config configs/carpet_metal_contamination_metal_contamination.yaml
python experiment.py --config configs/carpet_metal_contamination_foreign_objects.yaml
python experiment.py --config configs/carpet_metal_contamination_contaminated.yaml
python experiment.py --config configs/carpet_metal_contamination_broken.yaml
python experiment.py --config configs/carpet_metal_contamination_damage.yaml
python experiment.py --config configs/carpet_metal_contamination_damaged.yaml
python experiment.py --config configs/carpet_thread_thread.yaml
python experiment.py --config configs/carpet_thread_loose_thread.yaml
python experiment.py --config configs/carpet_thread_broken.yaml
python experiment.py --config configs/carpet_thread_damage.yaml
python experiment.py --config configs/carpet_thread_damaged.yaml
python experiment.py --config configs/grid_bent_bends.yaml
python experiment.py --config configs/grid_bent_bent_metal.yaml
python experiment.py --config configs/grid_bent_bent.yaml
python experiment.py --config configs/grid_bent_broken.yaml
python experiment.py --config configs/grid_bent_damage.yaml
python experiment.py --config configs/grid_bent_damaged.yaml
python experiment.py --config configs/grid_broken_broken_metal_grid.yaml
python experiment.py --config configs/grid_broken_damaged_metal.yaml
python experiment.py --config configs/grid_broken_broken.yaml
python experiment.py --config configs/grid_broken_damage.yaml
python experiment.py --config configs/grid_broken_damaged.yaml
python experiment.py --config configs/grid_glue_glue_drop.yaml
python experiment.py --config configs/grid_glue_glue.yaml
python experiment.py --config configs/grid_glue_liquid.yaml
python experiment.py --config configs/grid_glue_broken.yaml
python experiment.py --config configs/grid_glue_damage.yaml
python experiment.py --config configs/grid_glue_damaged.yaml
python experiment.py --config configs/grid_metal_contamination_excess_metal.yaml
python experiment.py --config configs/grid_metal_contamination_extra_metal.yaml
python experiment.py --config configs/grid_metal_contamination_metal_contamination.yaml
python experiment.py --config configs/grid_metal_contamination_broken.yaml
python experiment.py --config configs/grid_metal_contamination_damage.yaml
python experiment.py --config configs/grid_metal_contamination_damaged.yaml
python experiment.py --config configs/grid_thread_thread.yaml
python experiment.py --config configs/grid_thread_wool.yaml
python experiment.py --config configs/grid_thread_broken.yaml
python experiment.py --config configs/grid_thread_damage.yaml
python experiment.py --config configs/grid_thread_damaged.yaml
python experiment.py --config configs/hazelnut_crack_crack.yaml
python experiment.py --config configs/hazelnut_crack_cracked.yaml
python experiment.py --config configs/hazelnut_crack_error.yaml
python experiment.py --config configs/hazelnut_crack_hole.yaml
python experiment.py --config configs/hazelnut_crack_broken.yaml
python experiment.py --config configs/hazelnut_crack_damage.yaml
python experiment.py --config configs/hazelnut_crack_damaged.yaml
python experiment.py --config configs/hazelnut_cut_cut.yaml
python experiment.py --config configs/hazelnut_cut_error.yaml
python experiment.py --config configs/hazelnut_cut_hole.yaml
python experiment.py --config configs/hazelnut_cut_notch.yaml
python experiment.py --config configs/hazelnut_cut_scratch.yaml
python experiment.py --config configs/hazelnut_cut_split.yaml
python experiment.py --config configs/hazelnut_cut_broken.yaml
python experiment.py --config configs/hazelnut_cut_damage.yaml
python experiment.py --config configs/hazelnut_cut_damaged.yaml
python experiment.py --config configs/hazelnut_hole_crack.yaml
python experiment.py --config configs/hazelnut_hole_cracked.yaml
python experiment.py --config configs/hazelnut_hole_error.yaml
python experiment.py --config configs/hazelnut_hole_hole.yaml
python experiment.py --config configs/hazelnut_hole_holes.yaml
python experiment.py --config configs/hazelnut_hole_broken.yaml
python experiment.py --config configs/hazelnut_hole_damage.yaml
python experiment.py --config configs/hazelnut_hole_damaged.yaml
python experiment.py --config configs/hazelnut_print_white_color.yaml
python experiment.py --config configs/hazelnut_print_white_print.yaml
python experiment.py --config configs/hazelnut_print_white_letters.yaml
python experiment.py --config configs/hazelnut_print_print.yaml
python experiment.py --config configs/hazelnut_print_letters.yaml
python experiment.py --config configs/hazelnut_print_letter.yaml
python experiment.py --config configs/hazelnut_print_text.yaml
python experiment.py --config configs/hazelnut_print_color.yaml
python experiment.py --config configs/hazelnut_print_broken.yaml
python experiment.py --config configs/hazelnut_print_damage.yaml
python experiment.py --config configs/hazelnut_print_damaged.yaml
python experiment.py --config configs/leather_color_color.yaml
python experiment.py --config configs/leather_color_colored_strokes.yaml
python experiment.py --config configs/leather_color_stains.yaml
python experiment.py --config configs/leather_color_broken.yaml
python experiment.py --config configs/leather_color_damage.yaml
python experiment.py --config configs/leather_color_damaged.yaml
python experiment.py --config configs/leather_cut_scratch.yaml
python experiment.py --config configs/leather_cut_split.yaml
python experiment.py --config configs/leather_cut_cut.yaml
python experiment.py --config configs/leather_cut_broken.yaml
python experiment.py --config configs/leather_cut_damage.yaml
python experiment.py --config configs/leather_cut_damaged.yaml
python experiment.py --config configs/leather_fold_fold.yaml
python experiment.py --config configs/leather_fold_crease.yaml
python experiment.py --config configs/leather_fold_dents.yaml
python experiment.py --config configs/leather_fold_broken.yaml
python experiment.py --config configs/leather_fold_damage.yaml
python experiment.py --config configs/leather_fold_damaged.yaml
python experiment.py --config configs/leather_glue_glue_drop.yaml
python experiment.py --config configs/leather_glue_glue.yaml
python experiment.py --config configs/leather_glue_liquid.yaml
python experiment.py --config configs/leather_glue_broken.yaml
python experiment.py --config configs/leather_glue_damage.yaml
python experiment.py --config configs/leather_glue_damaged.yaml
python experiment.py --config configs/leather_poke_poke.yaml
python experiment.py --config configs/leather_poke_hole.yaml
python experiment.py --config configs/leather_poke_dents.yaml
python experiment.py --config configs/leather_poke_broken.yaml
python experiment.py --config configs/leather_poke_damage.yaml
python experiment.py --config configs/leather_poke_damaged.yaml
python experiment.py --config configs/metal_nut_bent_bent.yaml
python experiment.py --config configs/metal_nut_bent_bent_metal.yaml
python experiment.py --config configs/metal_nut_bent_broken.yaml
python experiment.py --config configs/metal_nut_bent_damage.yaml
python experiment.py --config configs/metal_nut_bent_damaged.yaml
python experiment.py --config configs/metal_nut_color_color.yaml
python experiment.py --config configs/metal_nut_color_colored_strokes.yaml
python experiment.py --config configs/metal_nut_color_broken.yaml
python experiment.py --config configs/metal_nut_color_damage.yaml
python experiment.py --config configs/metal_nut_color_damaged.yaml
python experiment.py --config configs/metal_nut_flip_flip.yaml
python experiment.py --config configs/metal_nut_flip_flipped_nut.yaml
python experiment.py --config configs/metal_nut_flip_broken.yaml
python experiment.py --config configs/metal_nut_flip_damage.yaml
python experiment.py --config configs/metal_nut_flip_damaged.yaml
python experiment.py --config configs/metal_nut_scratch_scratch.yaml
python experiment.py --config configs/metal_nut_scratch_scratched.yaml
python experiment.py --config configs/metal_nut_scratch_scratches.yaml
python experiment.py --config configs/metal_nut_scratch_cut.yaml
python experiment.py --config configs/metal_nut_scratch_broken.yaml
python experiment.py --config configs/metal_nut_scratch_damage.yaml
python experiment.py --config configs/metal_nut_scratch_damaged.yaml
python experiment.py --config configs/pill_color_color.yaml
python experiment.py --config configs/pill_color_colored_dots.yaml
python experiment.py --config configs/pill_color_colored_strokes.yaml
python experiment.py --config configs/pill_color_broken.yaml
python experiment.py --config configs/pill_color_damage.yaml
python experiment.py --config configs/pill_color_damaged.yaml
python experiment.py --config configs/pill_contamination_contamination.yaml
python experiment.py --config configs/pill_contamination_excess_material.yaml
python experiment.py --config configs/pill_contamination_foreign_objects.yaml
python experiment.py --config configs/pill_contamination_broken.yaml
python experiment.py --config configs/pill_contamination_damage.yaml
python experiment.py --config configs/pill_contamination_damaged.yaml
python experiment.py --config configs/pill_crack_crack.yaml
python experiment.py --config configs/pill_crack_cracked.yaml
python experiment.py --config configs/pill_crack_broken.yaml
python experiment.py --config configs/pill_crack_damage.yaml
python experiment.py --config configs/pill_crack_damaged.yaml
python experiment.py --config configs/pill_faulty_imprint_faulty_imprint.yaml
python experiment.py --config configs/pill_faulty_imprint_faulty_text.yaml
python experiment.py --config configs/pill_faulty_imprint_broken.yaml
python experiment.py --config configs/pill_faulty_imprint_damage.yaml
python experiment.py --config configs/pill_faulty_imprint_damaged.yaml
python experiment.py --config configs/pill_pill_type_pill_type.yaml
python experiment.py --config configs/pill_pill_type_wrong_pill.yaml
python experiment.py --config configs/pill_pill_type_different_pill.yaml
python experiment.py --config configs/pill_pill_type_broken.yaml
python experiment.py --config configs/pill_pill_type_damage.yaml
python experiment.py --config configs/pill_pill_type_damaged.yaml
python experiment.py --config configs/pill_scratch_scratch.yaml
python experiment.py --config configs/pill_scratch_scratched.yaml
python experiment.py --config configs/pill_scratch_scratches.yaml
python experiment.py --config configs/pill_scratch_cut.yaml
python experiment.py --config configs/pill_scratch_broken.yaml
python experiment.py --config configs/pill_scratch_damage.yaml
python experiment.py --config configs/pill_scratch_damaged.yaml
python experiment.py --config configs/screw_manipulated_front_damaged_screw.yaml
python experiment.py --config configs/screw_manipulated_front_malformed_screw.yaml
python experiment.py --config configs/screw_manipulated_front_broken.yaml
python experiment.py --config configs/screw_manipulated_front_damage.yaml
python experiment.py --config configs/screw_manipulated_front_damaged.yaml
python experiment.py --config configs/screw_scratch_head_scratch.yaml
python experiment.py --config configs/screw_scratch_head_scratched_screw.yaml
python experiment.py --config configs/screw_scratch_head_broken.yaml
python experiment.py --config configs/screw_scratch_head_damage.yaml
python experiment.py --config configs/screw_scratch_head_damaged.yaml
python experiment.py --config configs/screw_scratch_neck_scratch.yaml
python experiment.py --config configs/screw_scratch_neck_scratched_screw.yaml
python experiment.py --config configs/screw_scratch_neck_broken.yaml
python experiment.py --config configs/screw_scratch_neck_damage.yaml
python experiment.py --config configs/screw_scratch_neck_damaged.yaml
python experiment.py --config configs/screw_thread_side_broken_thread.yaml
python experiment.py --config configs/screw_thread_side_damaged_screw.yaml
python experiment.py --config configs/screw_thread_side_damaged_thread.yaml
python experiment.py --config configs/screw_thread_side_broken.yaml
python experiment.py --config configs/screw_thread_side_damage.yaml
python experiment.py --config configs/screw_thread_side_damaged.yaml
python experiment.py --config configs/screw_thread_top_broken_thread.yaml
python experiment.py --config configs/screw_thread_top_damaged_screw.yaml
python experiment.py --config configs/screw_thread_top_damaged_thread.yaml
python experiment.py --config configs/screw_thread_top_broken.yaml
python experiment.py --config configs/screw_thread_top_damage.yaml
python experiment.py --config configs/screw_thread_top_damaged.yaml
python experiment.py --config configs/tile_crack_crack.yaml
python experiment.py --config configs/tile_crack_cracked.yaml
python experiment.py --config configs/tile_crack_cracks.yaml
python experiment.py --config configs/tile_crack_broken.yaml
python experiment.py --config configs/tile_crack_damage.yaml
python experiment.py --config configs/tile_crack_damaged.yaml
python experiment.py --config configs/tile_glue_strip_glue_strip.yaml
python experiment.py --config configs/tile_glue_strip_tape.yaml
python experiment.py --config configs/tile_glue_strip_broken.yaml
python experiment.py --config configs/tile_glue_strip_damage.yaml
python experiment.py --config configs/tile_glue_strip_damaged.yaml
python experiment.py --config configs/tile_gray_stroke_gray_stroke.yaml
python experiment.py --config configs/tile_gray_stroke_grey_stroke.yaml
python experiment.py --config configs/tile_gray_stroke_big_gray_stroke.yaml
python experiment.py --config configs/tile_gray_stroke_broken.yaml
python experiment.py --config configs/tile_gray_stroke_damage.yaml
python experiment.py --config configs/tile_gray_stroke_damaged.yaml
python experiment.py --config configs/tile_oil_oil.yaml
python experiment.py --config configs/tile_oil_oil_film.yaml
python experiment.py --config configs/tile_oil_oil_drops.yaml
python experiment.py --config configs/tile_oil_oil_drop.yaml
python experiment.py --config configs/tile_oil_liquid.yaml
python experiment.py --config configs/tile_oil_broken.yaml
python experiment.py --config configs/tile_oil_damage.yaml
python experiment.py --config configs/tile_oil_damaged.yaml
python experiment.py --config configs/tile_rough_rough.yaml
python experiment.py --config configs/tile_rough_scratch.yaml
python experiment.py --config configs/tile_rough_roughened_surface.yaml
python experiment.py --config configs/tile_rough_broken.yaml
python experiment.py --config configs/tile_rough_damage.yaml
python experiment.py --config configs/tile_rough_damaged.yaml
python experiment.py --config configs/toothbrush_defective_defective.yaml
python experiment.py --config configs/toothbrush_defective_defective_toothbrush.yaml
python experiment.py --config configs/toothbrush_defective_broken.yaml
python experiment.py --config configs/toothbrush_defective_damage.yaml
python experiment.py --config configs/toothbrush_defective_damaged.yaml
python experiment.py --config configs/transistor_bent_lead_bent_lead.yaml
python experiment.py --config configs/transistor_bent_lead_damaged_lead.yaml
python experiment.py --config configs/transistor_bent_lead_broken.yaml
python experiment.py --config configs/transistor_bent_lead_damage.yaml
python experiment.py --config configs/transistor_bent_lead_damaged.yaml
python experiment.py --config configs/transistor_cut_lead_damaged_lead.yaml
python experiment.py --config configs/transistor_cut_lead_cut_lead.yaml
python experiment.py --config configs/transistor_cut_lead_broken.yaml
python experiment.py --config configs/transistor_cut_lead_damage.yaml
python experiment.py --config configs/transistor_cut_lead_damaged.yaml
python experiment.py --config configs/transistor_damaged_case_damaged_case.yaml
python experiment.py --config configs/transistor_damaged_case_damaged_transistor.yaml
python experiment.py --config configs/transistor_damaged_case_broken.yaml
python experiment.py --config configs/transistor_damaged_case_damage.yaml
python experiment.py --config configs/transistor_damaged_case_damaged.yaml
python experiment.py --config configs/transistor_misplaced_misplaced_transistor.yaml
python experiment.py --config configs/transistor_misplaced_missing_transistor.yaml
python experiment.py --config configs/transistor_misplaced_broken.yaml
python experiment.py --config configs/transistor_misplaced_damage.yaml
python experiment.py --config configs/transistor_misplaced_damaged.yaml
python experiment.py --config configs/wood_color_color.yaml
python experiment.py --config configs/wood_color_stains.yaml
python experiment.py --config configs/wood_color_color_stains.yaml
python experiment.py --config configs/wood_color_broken.yaml
python experiment.py --config configs/wood_color_damage.yaml
python experiment.py --config configs/wood_color_damaged.yaml
python experiment.py --config configs/wood_hole_hole.yaml
python experiment.py --config configs/wood_hole_crack.yaml
python experiment.py --config configs/wood_hole_drilled_hole.yaml
python experiment.py --config configs/wood_hole_broken.yaml
python experiment.py --config configs/wood_hole_damage.yaml
python experiment.py --config configs/wood_hole_damaged.yaml
python experiment.py --config configs/wood_liquid_liquid.yaml
python experiment.py --config configs/wood_liquid_spilt_liquid.yaml
python experiment.py --config configs/wood_liquid_drops.yaml
python experiment.py --config configs/wood_liquid_broken.yaml
python experiment.py --config configs/wood_liquid_damage.yaml
python experiment.py --config configs/wood_liquid_damaged.yaml
python experiment.py --config configs/wood_scratch_scratch.yaml
python experiment.py --config configs/wood_scratch_scratches.yaml
python experiment.py --config configs/wood_scratch_scratched_surface.yaml
python experiment.py --config configs/wood_scratch_broken.yaml
python experiment.py --config configs/wood_scratch_damage.yaml
python experiment.py --config configs/wood_scratch_damaged.yaml
python experiment.py --config configs/zipper_broken_teeth_broken_teeth.yaml
python experiment.py --config configs/zipper_broken_teeth_broken_tooth.yaml
python experiment.py --config configs/zipper_broken_teeth_split_teeth.yaml
python experiment.py --config configs/zipper_broken_teeth_broken_zipper.yaml
python experiment.py --config configs/zipper_broken_teeth_faulty_zipper.yaml
python experiment.py --config configs/zipper_broken_teeth_broken.yaml
python experiment.py --config configs/zipper_broken_teeth_damage.yaml
python experiment.py --config configs/zipper_broken_teeth_damaged.yaml
python experiment.py --config configs/zipper_fabric_border_damaged_fabric.yaml
python experiment.py --config configs/zipper_fabric_border_cut.yaml
python experiment.py --config configs/zipper_fabric_border_broken.yaml
python experiment.py --config configs/zipper_fabric_border_damage.yaml
python experiment.py --config configs/zipper_fabric_border_damaged.yaml
python experiment.py --config configs/zipper_fabric_interior_damaged_fabric.yaml
python experiment.py --config configs/zipper_fabric_interior_holes.yaml
python experiment.py --config configs/zipper_fabric_interior_damaged_surface.yaml
python experiment.py --config configs/zipper_fabric_interior_broken.yaml
python experiment.py --config configs/zipper_fabric_interior_damage.yaml
python experiment.py --config configs/zipper_fabric_interior_damaged.yaml
python experiment.py --config configs/zipper_rough_rough_teeth.yaml
python experiment.py --config configs/zipper_rough_rough_tooth.yaml
python experiment.py --config configs/zipper_rough_rough_edges.yaml
python experiment.py --config configs/zipper_rough_rough_zipper.yaml
python experiment.py --config configs/zipper_rough_broken.yaml
python experiment.py --config configs/zipper_rough_damage.yaml
python experiment.py --config configs/zipper_rough_damaged.yaml
python experiment.py --config configs/zipper_split_teeth_split_teeth.yaml
python experiment.py --config configs/zipper_split_teeth_broken_teeth.yaml
python experiment.py --config configs/zipper_split_teeth_broken_zipper.yaml
python experiment.py --config configs/zipper_split_teeth_faulty_zipper.yaml
python experiment.py --config configs/zipper_split_teeth_broken.yaml
python experiment.py --config configs/zipper_split_teeth_damage.yaml
python experiment.py --config configs/zipper_split_teeth_damaged.yaml
python experiment.py --config configs/zipper_squeezed_teeth_squeezed_teeth.yaml
python experiment.py --config configs/zipper_squeezed_teeth_broken_teeth.yaml
python experiment.py --config configs/zipper_squeezed_teeth_broken_zipper.yaml
python experiment.py --config configs/zipper_squeezed_teeth_broken.yaml
python experiment.py --config configs/zipper_squeezed_teeth_damage.yaml
python experiment.py --config configs/zipper_squeezed_teeth_damaged.yaml
