python experiment.py --config configs/1.yaml
python experiment.py --config configs/10.yaml
python experiment.py --config configs/11.yaml
python experiment.py --config configs/12.yaml
python experiment.py --config configs/13.yaml
python experiment.py --config configs/14.yaml
python experiment.py --config configs/15.yaml
python experiment.py --config configs/16.yaml
python experiment.py --config configs/17.yaml
python experiment.py --config configs/18.yaml
python experiment.py --config configs/19.yaml
python experiment.py --config configs/2.yaml
python experiment.py --config configs/20.yaml
python experiment.py --config configs/2345.yaml
python experiment.py --config configs/23454.yaml
python experiment.py --config configs/25436.yaml
python experiment.py --config configs/3.yaml
python experiment.py --config configs/32453.yaml
python experiment.py --config configs/34.yaml
python experiment.py --config configs/3434.yaml
python experiment.py --config configs/344.yaml
python experiment.py --config configs/3466777.yaml
python experiment.py --config configs/34trg.yaml
python experiment.py --config configs/35354.yaml
python experiment.py --config configs/4.yaml
python experiment.py --config configs/425435.yaml
python experiment.py --config configs/435.yaml
python experiment.py --config configs/43543565.yaml
python experiment.py --config configs/4442.yaml
python experiment.py --config configs/453453.yaml
python experiment.py --config configs/456563456.yaml
python experiment.py --config configs/4t3rez.yaml
python experiment.py --config configs/4zzz.yaml
python experiment.py --config configs/5.yaml
python experiment.py --config configs/5435.yaml
python experiment.py --config configs/5453.yaml
python experiment.py --config configs/54767.yaml
python experiment.py --config configs/54z5.yaml
python experiment.py --config configs/54zhg.yaml
python experiment.py --config configs/5558.yaml
python experiment.py --config configs/565656.yaml
python experiment.py --config configs/5678868.yaml
python experiment.py --config configs/56u5765.yaml
python experiment.py --config configs/57676.yaml
python experiment.py --config configs/6.yaml
python experiment.py --config configs/64564.yaml
python experiment.py --config configs/7.yaml
python experiment.py --config configs/7567567.yaml
python experiment.py --config configs/8.yaml
python experiment.py --config configs/9.yaml
python experiment.py --config configs/djj.yaml
python experiment.py --config configs/ett54t.yaml
python experiment.py --config configs/fdh.yaml
python experiment.py --config configs/gg.yaml
python experiment.py --config configs/ghgh.yaml
python experiment.py --config configs/ret45t.yaml
python experiment.py --config configs/rewtger.yaml
python experiment.py --config configs/thrhr.yaml
python experiment.py --config configs/zw4z.yaml
python aupro.py zipper
python aupro.py transistor
python aupro.py capsule
runs.bat