python aupro.py predictions/zipper/broken_teeth/broken.pt
python aupro.py predictions/zipper/broken_teeth/broken_teeth.pt
python aupro.py predictions/zipper/broken_teeth/damage.pt
python aupro.py predictions/zipper/broken_teeth/damaged.pt
python aupro.py predictions/zipper/broken_teeth/faulty_zipper.pt
python aupro.py predictions/zipper/broken_teeth/split_teeth.pt
python aupro.py predictions/zipper/fabric_border/broken.pt
python aupro.py predictions/zipper/fabric_border/cut.pt
python aupro.py predictions/zipper/fabric_border/damage.pt
python aupro.py predictions/zipper/fabric_border/damaged.pt
python aupro.py predictions/zipper/fabric_border/damaged_fabric.pt
python aupro.py predictions/zipper/fabric_interior/broken.pt
python aupro.py predictions/zipper/fabric_interior/damage.pt
python aupro.py predictions/zipper/fabric_interior/damaged.pt
python aupro.py predictions/zipper/fabric_interior/damaged_fabric.pt
python aupro.py predictions/zipper/fabric_interior/damaged_surface.pt
python aupro.py predictions/zipper/rough/broken.pt
python aupro.py predictions/zipper/rough/damage.pt
python aupro.py predictions/zipper/rough/damaged.pt
python aupro.py predictions/zipper/rough/rough_teeth.pt
python aupro.py predictions/zipper/rough/rough_zipper.pt
python aupro.py predictions/zipper/split_teeth/broken.pt
python aupro.py predictions/zipper/split_teeth/broken_teeth.pt
python aupro.py predictions/zipper/split_teeth/damage.pt
python aupro.py predictions/zipper/split_teeth/damaged.pt
python aupro.py predictions/zipper/split_teeth/faulty_zipper.pt
python aupro.py predictions/zipper/split_teeth/split_teeth.pt
python aupro.py predictions/zipper/squeezed_teeth/broken.pt
python aupro.py predictions/zipper/squeezed_teeth/broken_teeth.pt
python aupro.py predictions/zipper/squeezed_teeth/damage.pt
python aupro.py predictions/zipper/squeezed_teeth/damaged.pt
python aupro.py predictions/zipper/squeezed_teeth/faulty_zipper.pt
python aupro.py predictions/zipper/squeezed_teeth/squeezed_teeth.pt
python aupro.py predictions/transistor/damaged_case/broken.pt
python aupro.py predictions/transistor/damaged_case/damage.pt
python aupro.py predictions/transistor/damaged_case/damaged.pt
python aupro.py predictions/transistor/damaged_case/damaged_case.pt
python aupro.py predictions/transistor/damaged_case/damaged_transistor.pt
python aupro.py predictions/transistor/misplaced/broken.pt
python aupro.py predictions/transistor/misplaced/damage.pt
python aupro.py predictions/transistor/misplaced/damaged.pt
python aupro.py predictions/transistor/misplaced/misplaced_transistor.pt
python aupro.py predictions/transistor/misplaced/missing_transistor.pt
python aupro.py predictions/capsule/crack/broken.pt
python aupro.py predictions/capsule/crack/crack.pt
python aupro.py predictions/capsule/crack/cracked_capsule.pt
python aupro.py predictions/capsule/crack/damage.pt
python aupro.py predictions/capsule/crack/damaged.pt