python multi_figure_auroc.py metrics/bottle/broken_large
python multi_figure_auroc.py metrics/bottle/broken_small
python multi_figure_auroc.py metrics/bottle/contamination
python multi_figure_auroc.py metrics/cable/bent_wire
python multi_figure_auroc.py metrics/cable/cable_swap
python multi_figure_auroc.py metrics/cable/combined
python multi_figure_auroc.py metrics/cable/cut_inner_insulation
python multi_figure_auroc.py metrics/cable/cut_outer_insulation
python multi_figure_auroc.py metrics/cable/missing_cable
python multi_figure_auroc.py metrics/cable/missing_wire
python multi_figure_auroc.py metrics/cable/poke_insulation
python multi_figure_auroc.py metrics/capsule/crack
python multi_figure_auroc.py metrics/capsule/faulty_imprint
python multi_figure_auroc.py metrics/capsule/good
python multi_figure_auroc.py metrics/capsule/poke
python multi_figure_auroc.py metrics/capsule/scratch
python multi_figure_auroc.py metrics/capsule/squeeze
python multi_figure_auroc.py metrics/carpet/color
python multi_figure_auroc.py metrics/carpet/cut
python multi_figure_auroc.py metrics/carpet/hole
python multi_figure_auroc.py metrics/carpet/metal_contamination
python multi_figure_auroc.py metrics/carpet/thread
python multi_figure_auroc.py metrics/grid/bent
python multi_figure_auroc.py metrics/grid/broken
python multi_figure_auroc.py metrics/grid/glue
python multi_figure_auroc.py metrics/grid/metal_contamination
python multi_figure_auroc.py metrics/grid/thread
python multi_figure_auroc.py metrics/hazelnut/crack
python multi_figure_auroc.py metrics/hazelnut/cut
python multi_figure_auroc.py metrics/hazelnut/hole
python multi_figure_auroc.py metrics/hazelnut/print
python multi_figure_auroc.py metrics/leather/color
python multi_figure_auroc.py metrics/leather/cut
python multi_figure_auroc.py metrics/leather/fold
python multi_figure_auroc.py metrics/leather/glue
python multi_figure_auroc.py metrics/leather/poke
python multi_figure_auroc.py metrics/metal_nut/bent
python multi_figure_auroc.py metrics/metal_nut/color
python multi_figure_auroc.py metrics/metal_nut/flip
python multi_figure_auroc.py metrics/metal_nut/scratch
python multi_figure_auroc.py metrics/pill/color
python multi_figure_auroc.py metrics/pill/combined
python multi_figure_auroc.py metrics/pill/contamination
python multi_figure_auroc.py metrics/pill/crack
python multi_figure_auroc.py metrics/pill/faulty_imprint
python multi_figure_auroc.py metrics/pill/pill_type
python multi_figure_auroc.py metrics/pill/scratch
python multi_figure_auroc.py metrics/screw/manipulated_front
python multi_figure_auroc.py metrics/screw/scratch_head
python multi_figure_auroc.py metrics/screw/scratch_neck
python multi_figure_auroc.py metrics/screw/thread_side
python multi_figure_auroc.py metrics/screw/thread_top
python multi_figure_auroc.py metrics/tile/crack
python multi_figure_auroc.py metrics/tile/glue_strip
python multi_figure_auroc.py metrics/tile/gray_stroke
python multi_figure_auroc.py metrics/tile/oil
python multi_figure_auroc.py metrics/tile/rough
python multi_figure_auroc.py metrics/toothbrush/defective
python multi_figure_auroc.py metrics/transistor/bent_lead
python multi_figure_auroc.py metrics/transistor/cut_lead
python multi_figure_auroc.py metrics/transistor/damaged_case
python multi_figure_auroc.py metrics/transistor/misplaced
python multi_figure_auroc.py metrics/wood/color
python multi_figure_auroc.py metrics/wood/hole
python multi_figure_auroc.py metrics/wood/liquid
python multi_figure_auroc.py metrics/wood/scratch
python multi_figure_auroc.py metrics/zipper/broken_teeth
python multi_figure_auroc.py metrics/zipper/fabric_border
python multi_figure_auroc.py metrics/zipper/fabric_interior
python multi_figure_auroc.py metrics/zipper/rough
python multi_figure_auroc.py metrics/zipper/split_teeth
python multi_figure_auroc.py metrics/zipper/squeezed_teeth
